services:
  minimal-portforio-template:
    container_name: minimal-portforio-template
    image: minimal-portforio-template
    build:
      context: ./
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "4321:4321"
    restart: always
